name: deploy terraform

on:
  push:
    branches: 
      - main

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello from Octo Organization
      - name: checkout
        uses: actions/checkout@v4.1.1
      - name: get credentials
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          audience: https://token.actions.githubusercontent.com
          role-to-assume: ${{secrets.IAM_ROLE_ARN}}
          aws-region: "eu-west-1"
      - name: deploy terraform
        run: make plan
